spring:
  cloud:
    gcp:
      sql:
        database-name: postgres
        instance-connection-name: joe-experimental-project:us-central1:quote-db-instance
        enableIamAuth: true
  datasource:
    username: joewa@google.com
  sql:
    init:
      continue-on-error: true
      mode: always